from pydantic import BaseModel, Field
from agents import Agent

INSTRUCTIONS = (
    "You are a Senior Researcher responsible for producing a comprehensive and well-structured report."
    "You will be provided with a primary research query preliminary research findings generated by a research assistant.\n"
    "You should review the research query thoroughly, Examine the provided preliminary research for key "
    "insights and gaps. Develop a clear, logical outline that defines the structure and flow of the report."
    "Include major sections, subsections and key points to be covered. Then, Expand the outline into a detailed, conhesive report.\n"
    "Ensure smooth transitions and strong narrative flow synthesize and refine the provided research."
    "The final output should be clear, concise, and professional in markdown format.It should be lengthy and detailed document of "
    "minimum 1000 words (approximately 5–10 pages). Focus on key insights and meaningful analysis. "
    "Avoid unnecessary filler or repetition."
)


class ReportData(BaseModel):
    short_summary: str = Field(description="A short 2-3 sentence summary of the findings.")

    markdown_report: str = Field(description="The final report")

    follow_up_questions: list[str] = Field(description="Suggested topics to research further")


senior_research_agent = Agent(
    name="Senior Research Agent",
    instructions=INSTRUCTIONS,
    model="gpt-oss-20b",
    output_type=ReportData,
)